### ISSUE TITLE
Create new 2.10.0.x version 

### ISSUE THREAD

**Issue by ddieruf** [datastax/starlight-for-rabbitmq-docs#7]
Starlight for RabbitMQ latest release was promoted to 2.10.1.0 on Dec 21. Work to be done:

- create a new branch at release/2.10.1.x, based on release/2.10.0.x
- remove page-aliases from adoc files (this is a one-time action, the next branch will not need this)
- ensure all redirects for S4R are going to the 1.x version

https://github.com/datastax/starlight-for-rabbitmq/releases/tag/v2.10.1.0

**Comment by mendonk** [comment]
Redirects and release/2.10.1.x branch are ready to deploy.
